services:

  postgres:
    image: postgres:17

    container_name: invoice-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: faxx123
      POSTGRES_DB: invoices_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:

    build:
      context: ./backend

    container_name: invoice-backend

    ports:
      - "5000:5000"

    depends_on:
      - postgres

    # environment:
    #   DATABASE_URL: postgresql://admin:admin123@postgres:5432/invoices_db
    #   JWT_SECRET: super_secret_key

volumes:
  postgres_data: